In [2]:
import transformers
from transformers import TFBertForTokenClassification
import tensorflow as tf
from conllu import parse
import numpy as np
from data_preparation_pos import ABSATokenizerSATokenizer, convert_examples_to_tf_dataset

In [4]:
en_pos = open("../data/ud/en/en_pud-ud-test.conllu", "r", encoding="utf-8").read()
sentences = parse(en_pos)
tagset = ["O", "ADJ", "ADP", "ADV", "AUX", "CCONJ", "DET", "INTJ", "NOUN", "NUM", 
          "PART", "PRON", "PROPN", "PUNCT", "SCONJ", "SYM", "VERB", "X"]
tokenizer = ABSATokenizer.from_pretrained('bert-base-multilingual-cased')

In [5]:
dataset = convert_examples_to_tf_dataset(examples=sentences, tokenizer=tokenizer, tagset=tagset, max_length=512)
dataset = dataset.shuffle(100).batch(16).repeat(5)

In [7]:
list(iter(dataset))[0]

({'input_ids': <tf.Tensor: shape=(16, 512), dtype=int32, numpy=
  array([[  107, 16976, 10271, ...,     0,     0,     0],
         [10117, 99603,   130, ...,     0,     0,     0],
         [10117, 15824, 20199, ...,     0,     0,     0],
         ...,
         [  138, 41549, 32748, ...,     0,     0,     0],
         [12489, 10833,   100, ...,     0,     0,     0],
         [24314, 23127, 10189, ...,     0,     0,     0]])>,
  'attention_mask': <tf.Tensor: shape=(16, 512), dtype=int32, numpy=
  array([[1, 1, 1, ..., 0, 0, 0],
         [1, 1, 1, ..., 0, 0, 0],
         [1, 1, 1, ..., 0, 0, 0],
         ...,
         [1, 1, 1, ..., 0, 0, 0],
         [1, 1, 1, ..., 0, 0, 0],
         [1, 1, 1, ..., 0, 0, 0]])>,
  'token_type_ids': <tf.Tensor: shape=(16, 512), dtype=int32, numpy=
  array([[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0